## Preprocessing

In [24]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [25]:
# Drop the non-beneficial ID columns 'EIN' and 'NAME'
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [26]:
# Determine the number of unique values in each column
unique_counts = application_df.nunique()


print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [27]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [28]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Choose a cutoff value for replacing 
cutoff_value = 500  

# Create a list of application types to be replaced with "Other"
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in the dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [29]:
# Choose a cutoff value
cutoff_value = 100

# Find application types that occur less than or equal to the cutoff value
infrequent_application_types = application_df['APPLICATION_TYPE'].value_counts()[application_df['APPLICATION_TYPE'].value_counts() <= cutoff_value].index.tolist()

# Create a list of application types to be replaced with "Other"
application_types_to_replace = infrequent_application_types

# Replace in the DataFrame
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check the value counts after binning
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Look at CLASSIFICATION value counts where count is greater than 1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts_gt1 = classification_counts[classification_counts > 1]
print(classification_counts_gt1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [31]:
# Look at CLASSIFICATION value counts
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Choose a cutoff value for replacing less frequent classifications
cutoff_value = 100  

# Create a list of classifications to be replaced with "Other"
classifications_to_replace = classification_counts[classification_counts <= cutoff_value].index.tolist()

# Replace in the dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure binning was successful
classification_counts_after_binning = application_df['CLASSIFICATION'].value_counts()
print(classification_counts_after_binning)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [32]:
# List of categorical columns to be converted to dummies
categorical_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

# Apply pd.get_dummies to each categorical column
application_df_encoded = pd.get_dummies(application_df, columns=categorical_columns)

# Display the resulting DataFrame
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [33]:

X = application_df_encoded.drop(columns=['IS_SUCCESSFUL'])
y = application_df_encoded['IS_SUCCESSFUL']

# Import the train_test_split function
from sklearn.model_selection import train_test_split

# Split the data, with training set (70%) and a testing set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Print the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (24009, 49)
X_test shape: (10290, 49)
y_train shape: (24009,)
y_test shape: (10290,)

In [34]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [35]:
import tensorflow as tf

# Define the model 
nn = tf.keras.models.Sequential()

# Input layer with theinput features 
input_features = X_train.shape[1]

# First hidden layer with 32 nodes and ReLU activation function
nn.add(tf.keras.layers.Dense(units=32, activation='relu', input_dim=input_features))

# Second hidden layer with 16 nodes and ReLU activation function
nn.add(tf.keras.layers.Dense(units=16, activation='relu'))

# Output layer with a single node and sigmoid activation function 
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 32)                1600

 dense_4 (Dense)             (None, 16)                528

 dense_5 (Dense)             (None, 1)                 17

=================================================================
Total params: 2145 (8.38 KB)
Trainable params: 2145 (8.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [36]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [37]:
# Train the model
model_history = nn.fit(X_train, y_train, epochs=50, verbose=1)

Epoch 1/50
751/751 [==============================] - 3s 2ms/step - loss: 51404.5352 - accuracy: 0.4839
Epoch 2/50
751/751 [==============================] - 1s 2ms/step - loss: 94601.8906 - accuracy: 0.5064
Epoch 3/50
751/751 [==============================] - 2s 2ms/step - loss: 83202.2656 - accuracy: 0.4887
Epoch 4/50
751/751 [==============================] - 1s 2ms/step - loss: 9353.2129 - accuracy: 0.5135
Epoch 5/50
751/751 [==============================] - 2s 3ms/step - loss: 71850.2656 - accuracy: 0.4890
Epoch 6/50
751/751 [==============================] - 2s 3ms/step - loss: 38561.6758 - accuracy: 0.4863
Epoch 7/50
751/751 [==============================] - 1s 2ms/step - loss: 58240.8594 - accuracy: 0.5083
Epoch 8/50
751/751 [==============================] - 1s 2ms/step - loss: 43340.7461 - accuracy: 0.5042
Epoch 9/50
751/751 [==============================] - 1s 2ms/step - loss: 39385.6562 - accuracy: 0.5075
Epoch 10/50
751/751 [==============================] - 2s 2ms/step - loss: 27024.9297 - accuracy: 0.5086
Epoch 11/50
751/751 [==============================] - 1s 2ms/step - loss: 38356.1133 - accuracy: 0.5106
Epoch 12/50
751/751 [==============================] - 1s 2ms/step - loss: 15201.4531 - accuracy: 0.5157
Epoch 13/50
751/751 [==============================] - 2s 2ms/step - loss: 17591.0820 - accuracy: 0.5141
Epoch 14/50
751/751 [==============================] - 2s 3ms/step - loss: 35382.4023 - accuracy: 0.5350
Epoch 15/50
751/751 [==============================] - 2s 3ms/step - loss: 24280.9004 - accuracy: 0.5241
Epoch 16/50
751/751 [==============================] - 1s 2ms/step - loss: 18533.3379 - accuracy: 0.5142
Epoch 17/50
751/751 [==============================] - 1s 2ms/step - loss: 3677.9668 - accuracy: 0.5508
Epoch 18/50
751/751 [==============================] - 1s 2ms/step - loss: 3905.7061 - accuracy: 0.5510
Epoch 19/50
751/751 [==============================] - 2s 2ms/step - loss: 8733.2627 - accuracy: 0.5288
Epoch 20/50
751/751 [==============================] - 1s 2ms/step - loss: 9075.3438 - accuracy: 0.4973
Epoch 21/50
751/751 [==============================] - 1s 2ms/step - loss: 22678.4590 - accuracy: 0.5358
Epoch 22/50
751/751 [==============================] - 2s 2ms/step - loss: 16027.2646 - accuracy: 0.5172
Epoch 23/50
751/751 [==============================] - 2s 3ms/step - loss: 4384.4424 - accuracy: 0.5284
Epoch 24/50
751/751 [==============================] - 2s 2ms/step - loss: 12547.2773 - accuracy: 0.5257
Epoch 25/50
751/751 [==============================] - 1s 2ms/step - loss: 12705.6543 - accuracy: 0.5159
Epoch 26/50
751/751 [==============================] - 1s 2ms/step - loss: 4906.1401 - accuracy: 0.5483
Epoch 27/50
751/751 [==============================] - 1s 2ms/step - loss: 9981.5332 - accuracy: 0.5522
Epoch 28/50
751/751 [==============================] - 1s 2ms/step - loss: 3555.5127 - accuracy: 0.5654
Epoch 29/50
751/751 [==============================] - 1s 2ms/step - loss: 6944.8682 - accuracy: 0.5238
Epoch 30/50
751/751 [==============================] - 1s 2ms/step - loss: 13811.5645 - accuracy: 0.4940
Epoch 31/50
751/751 [==============================] - 2s 3ms/step - loss: 5301.1963 - accuracy: 0.5387
Epoch 32/50
751/751 [==============================] - 2s 3ms/step - loss: 11510.4658 - accuracy: 0.5310
Epoch 33/50
751/751 [==============================] - 2s 2ms/step - loss: 4028.6956 - accuracy: 0.5165
Epoch 34/50
751/751 [==============================] - 1s 2ms/step - loss: 1291.8494 - accuracy: 0.5370
Epoch 35/50
751/751 [==============================] - 1s 2ms/step - loss: 6037.3154 - accuracy: 0.5244
Epoch 36/50
751/751 [==============================] - 1s 2ms/step - loss: 5188.6240 - accuracy: 0.5400
Epoch 37/50
751/751 [==============================] - 1s 2ms/step - loss: 2918.7019 - accuracy: 0.5394
Epoch 38/50
751/751 [==============================] - 1s 2ms/step - loss: 1206.6672 - accuracy: 0.5572
Epoch 39/50
751/751 [==============================] - 2s 2ms/step - loss: 3953.8979 - accuracy: 0.5725
Epoch 40/50
751/751 [==============================] - 3s 3ms/step - loss: 943.4667 - accuracy: 0.5011
Epoch 41/50
751/751 [==============================] - 2s 3ms/step - loss: 1625.6979 - accuracy: 0.5036
Epoch 42/50
751/751 [==============================] - 1s 2ms/step - loss: 1470.1198 - accuracy: 0.4961
Epoch 43/50
751/751 [==============================] - 1s 2ms/step - loss: 1222.3367 - accuracy: 0.4888
Epoch 44/50
751/751 [==============================] - 1s 2ms/step - loss: 809.1954 - accuracy: 0.5097
Epoch 45/50
751/751 [==============================] - 1s 2ms/step - loss: 679.8707 - accuracy: 0.5245
Epoch 46/50
751/751 [==============================] - 1s 2ms/step - loss: 287.7126 - accuracy: 0.5365
Epoch 47/50
751/751 [==============================] - 2s 2ms/step - loss: 347.7872 - accuracy: 0.5237
Epoch 48/50
751/751 [==============================] - 2s 3ms/step - loss: 110.6001 - accuracy: 0.5251
Epoch 49/50
751/751 [==============================] - 2s 3ms/step - loss: 4.9588 - accuracy: 0.5329
Epoch 50/50
751/751 [==============================] - 2s 3ms/step - loss: 0.6837 - accuracy: 0.5310

In [38]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 1s - loss: 1.5147 - accuracy: 0.6962 - 777ms/epoch - 2ms/step
Loss: 1.5146706104278564, Accuracy: 0.6962099075317383

In [39]:
# Specify the file path where you want to save the model in Colab
model_filename = "/content/AlphabetSoupCharity.h5"

# Save the model to the Colab environment
nn.save(model_filename)

# Download the file to my computer
files.download(model_filename)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [40]:
from tensorflow import keras

# Load the model
loaded_model = keras.models.load_model('AlphabetSoupCharity.h5')


loaded_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 32)                1600

 dense_4 (Dense)             (None, 16)                528

 dense_5 (Dense)             (None, 1)                 17

=================================================================
Total params: 2145 (8.38 KB)
Trainable params: 2145 (8.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________